### ISSUE TITLE
BitCurator - KryoFlux

### ISSUE THREAD

**Issue by daremiyo** [RockefellerArchiveCenter/dm-transfer-workflow#5]
Is setup and command line instructions specific to Fred? or does it apply to both BitCurator and Fred?

**Comment by a-berish** [comment]
@daremiyo the Kryoflux has been installed on the BC machine as well as the FRED and would run the same way. The Kryoflux was installed on both machines when we thought that more than one person would be using the digital media transfer workstation. At this point though, we discovered that it might be best to leave the Kryoflux setup on the FRED machine only to avoid loosening wires that may end up throwing error messages. For documentation purposes, I think we should simplify this and note that the Kryoflux should be run on the FRED as the default machine (we would only run the Kryoflux on the BC machine for advanced troubleshooting purposes, or in the event that the FRED is unavailable for some reason).

**Comment by daremiyo** [comment]
thanks @a-berish !!
