### ISSUE TITLE
Formatting consistency

### ISSUE THREAD

**Issue by daremiyo** [RockefellerArchiveCenter/dm-transfer-workflow#6]
Workflow in process for a long time - general overview to see if content is consistently formatted
- for instance use of bold in transfer instruction for USBs and Hard Drives; should transfer instructions for other digital media types be similarly formatted?

**Comment by helrond** [comment]
I'm also seeing some inconsistent formatting indicating text to be entered in a command line. Would prefer that this be wrapped in tick marks and prefixed with a dollar sign `$ like this`.
